# Generated by Django 4.2.20 on 2025-05-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='сreated_at',
        ),
    ]
