# Generated by Django 4.2.20 on 2025-05-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_topic_name_remove_topic_сreated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='сreated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
